### ISSUE TITLE
Build failing couchbase-rs 0.3.0

### ISSUE THREAD

**Issue by anshul-mohil** [couchbaselabs/couchbase-rs#135]
### Problem:
Not able to build project with couchbase-rs 0.3.0(on mac os Big Sur 11.6) but able to build with couchbase = "1.0.0-alpha.4". It may suggest, either there is some niche configuration require to build  0.3.0 or there is a some issue(unlikely). In any case I think it's valuable to bring this issue into notice. 

### Current Setup:
Prerequisite libcouchbase setup: libcouchbase setup on mac using [couchbase documentation](https://docs.couchbase.com/c-sdk/current/hello-world/start-using-sdk.html#installation-on-mac-os-x).
```
>rustc --version
rustc 1.55.0 (c8dfcfe04 2021-09-06

[dependencies]
actix-web = "4.0.0-beta.9"
couchbase = "0.3.0"
#Note:  Working if switch to "1.0.0-alpha.4"
#couchbase = "1.0.0-alpha.4"
futures = "0.3.17"
serde = "1.0"
serde_json = "1.0"
async-std = "1.6"
log = "0.3.6"
```

### Build Issue:

```
> cargo build

thread 'main' panicked at 'No binding found for libcouchbase version 3.2.2 in the Rust SDK source', /Users/rust_user/.cargo/registry/src/github.com-1ecc6299db9ec823/couchbase-sys-0.3.0/build.rs:99:13
```

**Comment by chvck** [comment]
Hi @anshul-mohil thanks for using the SDK (we really value any feedback!) and for raising this. 0.3.0 was released a looong time ago, and I don't know if the SDK even shipped bundled with libcouchbase (like it does now) so might need libcouchbase to be manually installed - 0.3.0 is from well before I joined :) .

WHy are you wanting to use 0.3.0 over 1.0.0-alpha.4? The alpha is much more recent so more features and bugfixes.
