### ISSUE TITLE
Version 1.0.0-alpha.5 not available on crates.io

### ISSUE THREAD

**Issue by EliseChouleur** [couchbaselabs/couchbase-rs#157]
Hi,

I'd like to be on the latest version 1.0.0-alpha.5 as indicated in the README file but it's not available on crates.io :)

Thanks

**Comment by AndrewLipscomb** [comment]
Little bump on this one - crates.io is still rather out of date.

**Comment by raycardillo** [comment]
Closing per comment because there are no plans to publish the 1.0.0-alpha.5 version.
