### ISSUE TITLE
Support for libcouchbase-2.8.1

### ISSUE THREAD

**Issue by korczis** [couchbaselabs/couchbase-rs#34]
I am not able to make this working with libcouchbase-2.8.1.

Can you update the source code to support 2.8.1, please?

**Comment by daschl** [comment]
yep, I have a couple more changes in the queue and will do this too, hopefully I can get to work on the rust sdk a bit more in the coming weeks and months.

**Comment by daschl** [comment]
I've fixed it in couchbase-sys, maybe for now you want to manually override the dependency and use it from git until we've released 0.3 - I want to do more rework on the document abstractions first :)

**Comment by daschl** [comment]
Did a 0.3 release with 2.8.1 support :)
