### ISSUE TITLE
Should couchbase-sys include default=["build-lcb"]?

### ISSUE THREAD

**Issue by rcashie** [couchbaselabs/couchbase-rs#35]
The README states that if one runs with just the basic settings and executes `cargo build` the included `libcouchbase` library would be compiled.

That does not seem to be case however as I'm running into this error.

```
thread 'main' panicked at 'Need to build libcouchbase (none found), but the 'build-lcb' feature is not enabled!', .cargo/registry/src/github.com-1ecc6299db9ec823/couchbase-sys-0.3.0/build.rs:79:12
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It's the same error reported by doc.rs when it tries to build it: https://docs.rs/crate/couchbase/0.3.0/builds/72961

I'm fairly new to Rust and could be mistaken but should couchbase-sys have...
```
[features]
default=["build-lcb"]
```
.. so that it builds the library by default? That seems to allow me to build the lib locally. Or am I missing something?

**Comment by rcashie** [comment]
Placing this into my .toml file worked for me:
```
[features]
default = ["couchbase-sys/build-lcb"]
```

I'm not sure how one would turn off a feature if you do make it a default.

**Comment by rcashie** [comment]
This is the better way to do it (learning as I go along):

```
couchbase = "0.3.0"
couchbase-sys = { version = "0.3.0", features = ["build-lcb"]}
```

This unfortunately requires me to explicitly define in couchbase-sys as a dependency.
One option would be to expose feature `build-lcb` via the `couchbase` lib using a re-export.

Cargo.toml of couchbase:
```
build-lcb=["couchbase-sys/build-lcb"]
```
Cargo.toml of third party client:
```
couchbase = { version = "0.3.0", features = ["build-lcb"]}
```

**Comment by adilmobiliz** [comment]
@rcashie thanks, i had same issue on #12 

I followed your instruction and my issue has been resolved.

@daschl as @rcashie said, either way the readme should be updated.

thanks anyway

**Comment by adililhan** [comment]
@rcashie thanks a lot, i had same issue on #12

I followed your instruction and my issue has been resolved.

@daschl as @rcashie said, either way the readme should be updated.

thanks anyway...

**Comment by daschl** [comment]
@rcashie in the next version i'll make sure to pass the features down from `couchbase`, that will be in 0.4

**Comment by daschl** [comment]
In the upcoming 1.0.0-alpha.1 we are building lcb by default, since I think that might be the better option (we need to generate the ffi binding fresh anyways).

I'll close this one out, since I think it would also resolve this issue. Please reopen/feel free to create a new ticket if it doesn't work. If you want to try master, that would be awesome until we release the 1.0.0-alpha.1
