### ISSUE TITLE
Fully Implement Search API

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/couchbase-rs#4]
The Search API should be fully implemented based on the RFC found in https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0052-sdk3-full-text-search.md - this is part of the SDK 3 primary API surface.

Note that the search API is quite complex, looking at other reference implementations might be helpful. Please ask questions if needed when someones wants to pick it up.

**Comment by chvck** [comment]
This is done and superceded by #120
