### ISSUE TITLE
Failing to build with 0.4.0

### ISSUE THREAD

**Issue by j-brown** [couchbaselabs/couchbase-rs#40]
0.4.0 isn't published on crates.io, but I figured I could clone it locally and use it as a dependency.

One thing I had to do was change the futures dependency to "0.1.25", as the 0.2 beta has been removed.

my toml looks like this:

`
[package]
name = "test"
version = "0.1.0"

[dependencies]
couchbase = { version="0.4.0", path = "../couchbase-rs/couchbase"}
`

So I'm simply referencing a clone of the repo locally.
However, running cargo build throws an error:

`
Updating crates.io index
error: failed to select a version for `couchbase-sys`.
    ... required by package `couchbase v0.4.0 (/Users/me/rust/couchbase-rs/couchbase)`
    ... which is depended on by `test v0.1.0 (/Users/me/rust/test)`
versions that meet the requirements `= 0.4.0` are: 0.4.0

the package `couchbase` depends on `couchbase-sys`, with features: `build-lcb` but `couchbase-sys` does not have these features.

failed to select a version for `couchbase-sys` which could resolve this conflict
`
Does anyone know how to fix this?

**Comment by daschl** [comment]
@j-brown master again is now based on futures 0.1 until the rust folks have figured out where to move it next. Would you mind giving it a try? This would eventually become 1.0.0-alpha.1

**Comment by daschl** [comment]
Released 1.0.0-alpha.1, I'm closing this. Please reopen if you still see this, thanks!
