### ISSUE TITLE
Is there a missing 'lcb_n1p_free' call in 'query_n1ql'?

### ISSUE THREAD

**Issue by rcashie** [couchbaselabs/couchbase-rs#41]
`lcb_n1p_new` is called [here](https://github.com/couchbaselabs/couchbase-rs/blob/master/couchbase/src/bucket.rs#L304) to create a new instance of `lcb_N1QLPARAMS`. An associated call to `lcb_n1p_free` is not called however... was this intentional?

**Comment by daschl** [comment]
@rcashie thanks for reporting this.. the new code on master (which will become 1.0.0-alpha.1) includes the destroy calls properly!
