### ISSUE TITLE
linking with `cc` failed: exit code: 1 - Amazon Linux

### ISSUE THREAD

**Issue by tlebovic** [couchbaselabs/couchbase-rs#44]
With the latest version of couchbase-rs "1.0.0-alpha.1" linking errors occur after the build process completes successfully.  On my mac, the issue doesn't seem to manifest itself so it must be environmental dependencies but any help in tracking it down would be appreciated. 

**ld output:**
= note: /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::Instance::new::_$u7b$$u7b$closure$u7d$$u7d$::h9b78afbb32fd7f3f':
          /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/couchbase-1.0.0-alpha.1/src/instance/mod.rs:118: undefined reference to `lcb_create'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::Instance::new::_$u7b$$u7b$closure$u7d$$u7d$::h9b78afbb32fd7f3f':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance8Instance3new28_$u7b$$u7b$closure$u7d$$u7d$17h9b78afbb32fd7f3fE+0x257): undefined reference to `lcb_connect'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance8Instance3new28_$u7b$$u7b$closure$u7d$$u7d$17h9b78afbb32fd7f3fE+0x279): undefined reference to `lcb_wait'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance8Instance3new28_$u7b$$u7b$closure$u7d$$u7d$17h9b78afbb32fd7f3fE+0x310): undefined reference to `lcb_set_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance8Instance3new28_$u7b$$u7b$closure$u7d$$u7d$17h9b78afbb32fd7f3fE+0x517): undefined reference to `lcb_destroy'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance8Instance3new28_$u7b$$u7b$closure$u7d$$u7d$17h9b78afbb32fd7f3fE+0x52a): undefined reference to `lcb_tick_nowait'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::install_instance_callbacks::h6c6a6348ea34f29f':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance26install_instance_callbacks17h6c6a6348ea34f29fE+0x29): undefined reference to `lcb_install_callback3'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance26install_instance_callbacks17h6c6a6348ea34f29fE+0x4f): undefined reference to `lcb_install_callback3'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance26install_instance_callbacks17h6c6a6348ea34f29fE+0x75): undefined reference to `lcb_install_callback3'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance26install_instance_callbacks17h6c6a6348ea34f29fE+0x9b): undefined reference to `lcb_install_callback3'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance26install_instance_callbacks17h6c6a6348ea34f29fE+0xc1): undefined reference to `lcb_install_callback3'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o):couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance26install_instance_callbacks17h6c6a6348ea34f29fE+0xe7): more undefined references to `lcb_install_callback3' follow
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::decrement_outstanding_requests::hf4ab12da5538f896':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance30decrement_outstanding_requests17hf4ab12da5538f896E+0x15): undefined reference to `lcb_get_cookie'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::get_callback::h8f5430cc1c296706':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance12get_callback17h8f5430cc1c296706E+0x59): undefined reference to `lcb_respget_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance12get_callback17h8f5430cc1c296706E+0x87): undefined reference to `lcb_respget_status'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance12get_callback17h8f5430cc1c296706E+0x103): undefined reference to `lcb_respget_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance12get_callback17h8f5430cc1c296706E+0x11f): undefined reference to `lcb_respget_flags'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance12get_callback17h8f5430cc1c296706E+0x13b): undefined reference to `lcb_respget_value'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::store_callback::hbc7074aadebae8fb':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance14store_callback17hbc7074aadebae8fbE+0x59): undefined reference to `lcb_respstore_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance14store_callback17hbc7074aadebae8fbE+0x8d): undefined reference to `lcb_respstore_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance14store_callback17hbc7074aadebae8fbE+0xa6): undefined reference to `lcb_respstore_status'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::remove_callback::hb19bd02bc53abd41':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15remove_callback17hb19bd02bc53abd41E+0x59): undefined reference to `lcb_respremove_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15remove_callback17hb19bd02bc53abd41E+0x8d): undefined reference to `lcb_respremove_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15remove_callback17hb19bd02bc53abd41E+0xa6): undefined reference to `lcb_respremove_status'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::touch_callback::h67dc03aa9262cd44':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance14touch_callback17h67dc03aa9262cd44E+0x59): undefined reference to `lcb_resptouch_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance14touch_callback17h67dc03aa9262cd44E+0x8d): undefined reference to `lcb_resptouch_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance14touch_callback17h67dc03aa9262cd44E+0xa6): undefined reference to `lcb_resptouch_status'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::unlock_callback::h7a39376ace08ac6b':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15unlock_callback17h7a39376ace08ac6bE+0x59): undefined reference to `lcb_respunlock_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15unlock_callback17h7a39376ace08ac6bE+0x8d): undefined reference to `lcb_respunlock_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15unlock_callback17h7a39376ace08ac6bE+0xa6): undefined reference to `lcb_respunlock_status'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::exists_callback::h06c69ad42568d69d':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15exists_callback17h06c69ad42568d69dE+0x59): undefined reference to `lcb_respexists_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15exists_callback17h06c69ad42568d69dE+0x8d): undefined reference to `lcb_respexists_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15exists_callback17h06c69ad42568d69dE+0xa6): undefined reference to `lcb_respexists_status'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance15exists_callback17h06c69ad42568d69dE+0xc9): undefined reference to `lcb_respexists_is_found'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::lookup_in_callback::hdfa169695923a98c':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18lookup_in_callback17hdfa169695923a98cE+0x7c): undefined reference to `lcb_respsubdoc_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18lookup_in_callback17hdfa169695923a98cE+0xb3): undefined reference to `lcb_respsubdoc_status'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18lookup_in_callback17hdfa169695923a98cE+0xf1): undefined reference to `lcb_respsubdoc_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18lookup_in_callback17hdfa169695923a98cE+0x126): undefined reference to `lcb_respsubdoc_result_size'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18lookup_in_callback17hdfa169695923a98cE+0x2d9): undefined reference to `lcb_respsubdoc_result_value'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18lookup_in_callback17hdfa169695923a98cE+0x355): undefined reference to `lcb_respsubdoc_result_status'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.8.rcgu.o): In function `couchbase::instance::mutate_in_callback::h5eeaf09d34dc56eb':
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18mutate_in_callback17h5eeaf09d34dc56ebE+0x7c): undefined reference to `lcb_respsubdoc_cookie'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18mutate_in_callback17h5eeaf09d34dc56ebE+0xb3): undefined reference to `lcb_respsubdoc_status'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18mutate_in_callback17h5eeaf09d34dc56ebE+0xf1): undefined reference to `lcb_respsubdoc_cas'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18mutate_in_callback17h5eeaf09d34dc56ebE+0x136): undefined reference to `lcb_respsubdoc_result_size'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18mutate_in_callback17h5eeaf09d34dc56ebE+0x2e3): undefined reference to `lcb_respsubdoc_result_value'
          couchbase.9h5t1pit-cgu.8:(.text._ZN9couchbase8instance18mutate_in_callback17h5eeaf09d34dc56ebE+0x35f): undefined reference to `lcb_respsubdoc_result_status'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.0.rcgu.o): In function `_$LT$couchbase..instance..request..GetRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$::encode::h3ae1b49d32db4ba1':
          /home/ec2-user/.cargo/registry/src/github.com-1ecc6299db9ec823/couchbase-1.0.0-alpha.1/src/instance/request.rs:71: undefined reference to `lcb_cmdget_create'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.0.rcgu.o): In function `_$LT$couchbase..instance..request..GetRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$::encode::h3ae1b49d32db4ba1':
          couchbase.9h5t1pit-cgu.0:(.text._ZN106_$LT$couchbase..instance..request..GetRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h3ae1b49d32db4ba1E+0x22d): undefined reference to `lcb_cmdget_key'
          couchbase.9h5t1pit-cgu.0:(.text._ZN106_$LT$couchbase..instance..request..GetRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h3ae1b49d32db4ba1E+0x2f6): undefined reference to `lcb_cmdget_timeout'
          couchbase.9h5t1pit-cgu.0:(.text._ZN106_$LT$couchbase..instance..request..GetRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h3ae1b49d32db4ba1E+0x328): undefined reference to `lcb_get'
          couchbase.9h5t1pit-cgu.0:(.text._ZN106_$LT$couchbase..instance..request..GetRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h3ae1b49d32db4ba1E+0x33f): undefined reference to `lcb_cmdget_destroy'
          /home/ec2-user/projects/identity/target/debug/deps/libcouchbase-c063c9abe7ec4ca0.rlib(couchbase-c063c9abe7ec4ca0.couchbase.9h5t1pit-cgu.0.rcgu.o): In function `_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$::encode::h48ceb09025d1fc93':
          couchbase.9h5t1pit-cgu.0:(.text._ZN109_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h48ceb09025d1fc93E+0x2c8): undefined reference to `lcb_cmdstore_create'
          couchbase.9h5t1pit-cgu.0:(.text._ZN109_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h48ceb09025d1fc93E+0x328): undefined reference to `lcb_cmdstore_key'
          couchbase.9h5t1pit-cgu.0:(.text._ZN109_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h48ceb09025d1fc93E+0x354): undefined reference to `lcb_cmdstore_flags'
          couchbase.9h5t1pit-cgu.0:(.text._ZN109_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h48ceb09025d1fc93E+0x39f): undefined reference to `lcb_cmdstore_value'
          couchbase.9h5t1pit-cgu.0:(.text._ZN109_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h48ceb09025d1fc93E+0x468): undefined reference to `lcb_cmdstore_timeout'
          couchbase.9h5t1pit-cgu.0:(.text._ZN109_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h48ceb09025d1fc93E+0x49a): undefined reference to `lcb_store'
          couchbase.9h5t1pit-cgu.0:(.text._ZN109_$LT$couchbase..instance..request..UpsertRequest$u20$as$u20$couchbase..instance..request..InstanceRequest$GT$6encode17h48ceb09025d1fc93E+0x4b1): undefined reference to `lcb_cmdstore_destroy'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

**Comment by daschl** [comment]
Thanks for reporting! I‘ll see if I can reproduce this with a linux vm..

**Comment by tlebovic** [comment]
It looks like the llvm version was the cause of the problem. Thanks for getting back to me on this issue so quickly. Just for reference, the initial version of LLVM that was installed was:

```
 LLVM version 3.6.2
  Optimized build.
  Built Sep  4 2015 (23:11:46).
  Default target: x86_64-amazon-linux-gnu
  Host CPU: x86-64
```

Also unrelated to this issue but more of an SDK usability question. Why does the `default_collection().get()....` the method has a return type of `Result<Option<GetResult>, couchbase::CouchbaseError>` The double wrapping of Option inside a result seems overly cumbersome. To extract the document without much boilerplate, I ended up creating a new structure and a trait. This feels like either I am misusing the API or some convenience methods are missing.

**Comment by daschl** [comment]
@tlebovic thanks for the feedback! The `Result` is an indication that the request failed completely. The `Option` on the other hand will return `None` if the document does not exist. This is also how it will work in the new java sdk for example, but we are still debating if a non-existent document should be an error as well (unfortunately there is no perfect answer, since for some apps a non-existent doc is totally fine but for others it might be an error).

**Comment by daschl** [comment]
@tlebovic to whivh LLVM version did you upgrade on amazon linux to resolve the situation?

**Comment by tlebovic** [comment]
@daschl Thank you for the answer; I see your point. At least now, I know I wasn't missing anything obvious and will continue to use my custom struct & trait in my application to reduce the boilerplate. 

I upgraded the amazon Linux instance to LLVM 8

**Comment by daschl** [comment]
Thanks! Btw we are discussing getting rid of the Option piece so there is a chance it changes in the coming alphas... thanks again for the feedback!
