### ISSUE TITLE
Static Build with OpenSSL

### ISSUE THREAD

**Issue by tlebovic** [couchbaselabs/couchbase-rs#45]
I am trying to statically build my executable with musl. I need to be able to provide couchbase with a new location where I have compiled OpenSSL. I noticed that there is a `with-openssl` flag that can be used for that very purpose. However, I don't believe it's exposed when compiling couchbase-rs as a project dependency. Probably missing something very simple so apologies ahead of time.

**Comment by daschl** [comment]
You are right I don’t think this works yet - I haven’t had that come up before.

I‘ll check with @avsej and report back

**Comment by daschl** [comment]
He said libcouchbase accepts the path as `cmake -DOPENSSL_ROOT_DIR=/path` so I think we make the build.rs take an env variable and pass it down this might be an option @tlebovic?

**Comment by tlebovic** [comment]
Yeah, making build.rs expose that option through an environment variable would work nicely. If you want I can submit a PR.

**Comment by daschl** [comment]
@tlebovic thanks for the PR! Let's continue the discussion over there on the specific implementation.

**Comment by daschl** [comment]
A similar build.rs change is merged, so I think this can be closed. Thanks for all your help on this!
