### ISSUE TITLE
Future never resolves if an empty string is supplied as key in `collection.insert`

### ISSUE THREAD

**Issue by atsuzaki** [couchbaselabs/couchbase-rs#47]
This piece of code:
```rust
collection.insert("", &value, None).wait()?;
```
will block forever because (I suspect, atleast) the Future doesn't ever resolve.

**Comment by daschl** [comment]
@atsuzaki thanks for reporting! Is this on master or are you using a prerelease version?

**Comment by daschl** [comment]
this definitely needs checking in the code and resolve the future with a proper error.

**Comment by atsuzaki** [comment]
@daschl I'm on 1.0.0-alpha.2

**Comment by chvck** [comment]
I think that this is now working correctly.
