### ISSUE TITLE
Order is lost when doing a query

### ISSUE THREAD

**Issue by adamhjk** [couchbaselabs/couchbase-rs#49]
When performing a query, such as:

```
SELECT f.* FROM `f` WHERE typeName = "foo" ORDER BY bits
```

The results are returned in an arbitrary order. I suspect this is because the order itself is lost when we push things through the receiver and generate the resulting stream.

**Comment by adamhjk** [comment]
This is a problem, but it's not for the reason I thought.

The problem is when you use QueryOptions to bind in the Order position, I think. Since all the options are json values, they wind up with quotation marks in them, which is invalid. It probably means that the whole thing is not nearly as safe as, say, stored positional procedures in postgresql.

**Comment by adamhjk** [comment]
Nope! not that either, after digging in to the C api.

I think the real issue here is that you simply cannot have named or positional paraemeters in the ORDER BY expression

**Comment by adamhjk** [comment]
Hey @daschl - can you confirm that parameters are not valid outside of arguments? That you can't use a named or optional parameter in the ORDER BY position? If so I'll close this and stop digging. :)

**Comment by daschl** [comment]
Looks like someone from our query team answered (he also pointed me to that one) https://forums.couchbase.com/t/query-parameters-outside-the-where-clause/23409 does that help?

If not I can also look early next week

**Comment by adamhjk** [comment]
Yep - this isn't an actual issue. Sorry!
