### ISSUE TITLE
Investigate an IO plugin for libcouchbase

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/couchbase-rs#50]
Right now we run in our own event loop and use "blocking lcb" single threaded. It would be awesome if we could write our on FFI IO plugin for lcb (see https://github.com/couchbase/libcouchbase/tree/master/plugins/io) by making use of i.e. tokio. This would also allow lcb to run cooperatively in tokio if through a config a custom executor is passed in.

This is definitely considered an advanced ticket and needs some research/prototyping first.

**Comment by adamhjk** [comment]
Wouldn't it be easier to just write a rust-native couchbase client?

**Comment by daschl** [comment]
@adamhjk better yes, easier not likely.

I think I should've done a better job articulating my thoughts on that issue tracker or in a readme, but I'll start a quick braindump here.

I've always wanted to do a fully native rust couchbase client, but a couple things have held me back in the past:

- the amount of effort. I'm maintaining the full java sdk which includes all the connection management, failover and rebalance logic. Thats a good bunch of code to write but then also to maintain for future versions. This is why building on top of lcb for now gives us a "get out of jail free" card because lcb does all of that and we "just" have to put the rust API on top - with all its negative implications of course.
- the SDK 3.0 API being in flux. We are now really closing in on the home stretch for the other officially maintained SDK apis ("3.0") alongside server 6.5 which also includes a brand new API. I think at this point it has stabilized enough that we can think about bringing that over to the rust SDK.
- and honestly futures 0.1 was a little painful to work in, that is now also gone with async await and tokio / hyper coming together on top of it. I think we can even abstract those parts into a runtime component so we can also use async-std (we only need tcp sockets, http sockets and timers mostly). 

So with all this perspective, I was originally planning to do a Rust SDK 1.0 on top of libcouchbase so users have something they can work with and if enough users pick it up and we can justify the work do a full native rust sdk. I think once LCB becomes stable (there is a beta.2) coming out soon we can move closer to something shippable for 1.0 here.

Also once Java 3.0 ships I should have a little more time on my hands to also push this forward more aggressively. And then once the "pressure" is off, we can think about porting i.e. the java SDK which is built on top of netty, so very similar concepts at its core, over to rust and get to a full native one (but realistically that is many months away).

**Comment by adamhjk** [comment]
Thanks for the explanation! I'm happy to help out around the edges. :)

**Comment by daschl** [comment]
@adamhjk if you are curious, I started working on a pure rust sdk in the native branch (https://github.com/couchbaselabs/couchbase-rs/tree/native) .. it's still very early days and I'm iterating on it.. but as soon as I have something working that is at least barely usable I'll let you know

**Comment by adamhjk** [comment]
Dope! I'm happy to lend a hand if there are things that can be easily delegated - especially if you've already got the basics of the wire protocol in, and it's just filling out behavior.

**Comment by daschl** [comment]
Awesome! If you are up for it, I'd love to talk you through the architecture at some point and get your feedback.

**Comment by daschl** [comment]
ok some progress. I rewrote the current client so that it supports a pluggable IO layer. Right now only lcb is in there, but it is structured to add the native code later. This will allow us to get something out of the door more quickly and then add native in the future (and users can enable it via a feature flag). once it is complete and mature we can flip the default feature around.
