### ISSUE TITLE
n1ql scan consistency

### ISSUE THREAD

**Issue by adamhjk** [couchbaselabs/couchbase-rs#53]
It appears that we can't set the n1ql `scan_consistency` parameter, meaning that every request can just be stale. This is sometimes fine (and fast!) but is problematic when you need to read-your-own-writes.

https://docs.couchbase.com/server/6.5/settings/query-settings.html#scan_consistency

**Comment by daschl** [comment]
Yes, this needs to be folded in. In the end it should pretty much mirror these from java: https://docs.couchbase.com/sdk-api/couchbase-java-client-3.0.0-beta.2/com/couchbase/client/java/query/QueryOptions.html . The spec to align can be found here for the curious: https://docs.google.com/document/d/1MigpPIoEc-srXRJb7bUel3qTlGPvI-be-hT0jkGNNAY/edit

**Comment by adamhjk** [comment]
Great - I'm on it.

**Comment by adamhjk** [comment]
That google doc is closed to me - mind opening it up? I would love to see it.

**Comment by daschl** [comment]
@adamhjk sorry it should've been public anyways - does it work now?

**Comment by adamhjk** [comment]
@daschl yes, it's open now. thanks!

**Comment by daschl** [comment]
Merged into master, so closing this. thanks!
