### ISSUE TITLE
Can not complied Couchbase with Rust

### ISSUE THREAD

**Issue by vietlib** [couchbaselabs/couchbase-rs#54]
I have tried the demo code but can not complied. The error show below, can you help me fix this please 
=======================
error: failed to run custom build command for `couchbase-sys v1.0.0-alpha.2`

Caused by:
  process didn't exit successfully: `E:\rust\couchbase\target\debug\build\couchbase-sys-143e5e6ff4cbc438\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "C:\\Users\\PANDA\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\couchbase-sys-1.0.0-alpha.2\\libcouchbase" "-G" "Visual Studio 15 2017" "-Thost=x64" "-Ax64" "-DCMAKE_BUILD_TYPE=DEBUG" "-DLCB_NO_TESTS=ON" "-DLCB_NO_TOOLS=ON" "-DLCB_NO_MOCK=ON" "-DLCB_BUILD_LIBEV=OFF" "-DLCB_BUILD_LIBUV=OFF" "-DCMAKE_INSTALL_PREFIX=E:\\rust\\couchbase\\target\\debug\\build\\couchbase-sys-044b55446932b13a\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro"
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18362.
-- Found UV include dir: LIBUV_INCLUDE_DIR-NOTFOUND
-- Sanitized VERSION=
-- libcouchbase 3,0,0-alpha
-- Building libcouchbase 3.0.0-alpha.2/0xdeadbeef
-- SSL Found
-- Configuring done
-- Generating done
-- Build files have been written to: E:/rust/couchbase/target/debug/build/couchbase-sys-044b55446932b13a/out/build
running: "cmake" "--build" "." "--target" "install" "--config" "Debug" "--"
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\contrib\cbsasl\cbsasl-lcb.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\contrib\cliopts\cliopts.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\plugins\io\iocp\couchbase_iocp.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\plugins\io\select\couchbase_select.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\couchbase_utils.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\contrib\lcb-jsoncpp\lcb_jsoncpp.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\lcb_jsparse.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\contrib\snappy\lcb_snappy.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\lcbcore.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\lcbcore-cxx.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\lcbht.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\lcbio.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\lcbio-cxx.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\src\ssl\lcbssl.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\mcreq.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\mcreq-cxx.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\netbuf.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\netbuf-malloc.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\rdb.vcxproj]
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [E:\rust\couchbase\target\debug\build\couchbase-sys-044b55446932b13a\out\build\src\vbucket\vbucket-lcb.vcxproj]

--- stderr
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
CMake Deprecation Warning at cmake/Modules/CopyPDB.cmake:2 (CMAKE_POLICY):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:86 (INCLUDE)

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\PANDA\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.42\src\lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by chvck** [comment]
I *think* that this is now fixed, and was a specific failure to build on Windows.
