### ISSUE TITLE
Add all QueryOptions as per RFC

### ISSUE THREAD

**Issue by daschl** [couchbaselabs/couchbase-rs#57]
The QueryOptions need to be exposed like defined in https://docs.google.com/document/d/1MigpPIoEc-srXRJb7bUel3qTlGPvI-be-hT0jkGNNAY/edit?usp=sharing and also need to be sent down to lcb

**Comment by daschl** [comment]
This needs to be double checked I think

**Comment by chvck** [comment]
Looks like they're all there to me.
