### ISSUE TITLE
fields option for search_query

### ISSUE THREAD

**Issue by littlebunch** [couchbaselabs/couchbase-rs#70]
It would be very useful to have the fields option (and maybe explain too) available for search_query.  Something like

`SearchOptions::default().raw(json!({"Fields": ["*"]}))` or `SearchOptions::default().fields("*")`.   

Just wondering if there are plans for this?

**Comment by daschl** [comment]
yeah, we are planning to add the "full" search API as the other SDKs have, for now we only implemented the bare minimum to get started. Thanks for raising it, we'll definitely have it eventually

**Comment by daschl** [comment]
Linking #4 since that will covert it as well.

**Comment by chvck** [comment]
I think that this is done now.
